from .super import ModelManager
from .base import BaseModelManager
from .aitemplate import AITemplateModelManager
from .blip import BlipModelManager
from .clip import ClipModelManager
from .codeformer import CodeFormerModelManager
from .compvis import CompVisModelManager
from .esrgan import EsrganModelManager
from .gfpgan import GfpganModelManager
